// import type { Metadata } from "next";
'use client'
import { Inter } from "next/font/google";
import '../globals.css'
// import '../../globals.css'
import { Categories } from "@/widgets/store-page/categories";
import { createContext, useState } from "react";
import { useParams } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Razor Store Page",
//   description: "Generated by create next app",
// };

// console.log(params);

export const CategoryContext = createContext('Category');



// export default function StoreLayout( { children } : Readonly <{children: React.ReactNode}> ){
  export default function StoreLayout( { children } ){
    const [currentCategory, setCurrentCategory] = useState('');
    const params = useParams();
    // console.log(params);

  return (
      <>
        {/* <CategoryContext.Provider value={{currentCategory, setCurrentCategory}}> */}
            <Categories></Categories>
            {children}
        {/* </ CategoryContext.Provider> */}
    </>

  );
}